services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - back/.env
